### ISSUE TITLE
Add meta data

### ISSUE THREAD

**Issue by adamf321** [moxie-leean/wp-endpoints-post#15]
Output the meta data with each post.
Do we rely on Yoast to provide the UI?

**Comment by jeffreynolte** [comment]
@adamf321 - confirming Yoast

**Comment by mitogh** [comment]
Example: https://gist.github.com/mitogh/2a1a56019691d65579567041d07980e3

**Comment by adamf321** [comment]
@mitogh we need to do the same for authors and collection. Do you know offhand how Yoast stores that data? I'm not sure if we can share code between the endpoints or if it will be quite specific to each. Though the most re-usable way to implement this would be to have a wp-yoast package which holds all the yoast specific stuff (like we have a wp-acf).
